[[mavenize]]
=== Mavenize Your Application

Windup 2.6 introduces the ability to generate an Apache Maven project structure based on the applications provided. This will create a directory structure with the necessary Maven Project Object Model (POM) files that specify the appropriate dependencies.

Note that this feature is not intended to create a final solution for your project. It is meant to give you a starting point and identify the necessary dependencies and APIs for your applications. Your project may require further customization.

==== Generate the Maven Project Structure

You can generate a Maven project structure by passing in the `--mavenize` flag when executing Windup.

The following example runs Windup using the link:https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] test application.

[source,options="nowrap"]
----
$ WINDUP_HOME/bin/windup --input /path/to/jee-example-app-1.0.0.ear --output /path/to/output --target eap --packages com.acme org.apache --mavenize
----

This will generate the Maven project structure in the `/path/to/output/mavenized` directory.

// TODO what happens if you try to run it against source code?
NOTE: You can only use the `--mavenize` option when providing a compiled application for the `--input` argument. This feature is not available when running against source code.

// TODO mention the --mavenizeGroupId flag.  Here? or when evaluating POM files?

==== Review the Maven Project Structure

The `/path/to/output/mavenized` directory will contain the following items:

* A xref:root_pom_file[root POM file]. This is the `pom.xml` file at the top-level directory.
* A xref:bom_file[BOM file]. This is the POM file in the directory ending with `-bom`.
* One or more xref:app_pom_files[application POM files]. Each module has its POM file in a directory named after the archive.

The example `jee-example-app-1.0.0.ear` application is an EAR archive that contains a WAR and several JARs. There is a separate directory created for each of these artifacts. Below is the Maven project structure created for this application.

[source,options="nowrap"]
----
/path/to/output/mavenized/
    jee-example-app-bom/pom.xml
    jee-example-app-ear/pom.xml
    jee-example-services2-jar/pom.xml
    jee-example-services-jar/pom.xml
    jee-example-web-war/pom.xml
    pom.xml
----

To learn more about Maven POM files, see the link:https://maven.apache.org/guides/introduction/introduction-to-the-pom.html[Introduction to the POM] section of the Apache Maven documentation.

[[root_pom_file]]
===== Root POM File

The root POM file for the `jee-example-app-1.0.0.ear` application can be found at `/path/to/output/mavenized/pom.xml`. This file identifies the directories for all of the project modules.

The following modules are listed in the root POM for the example `jee-example-app-1.0.0.ear` application.

// TODO: I manually reversed the order here to be more appropriate. The order may be fixed in a future Windup JIRA. Also verify whether BOM should be in this list, and if so, where?
[source,xml,options="nowrap"]
----
<modules>
  <module>jee-example-services2-jar</module>
  <module>jee-example-services-jar</module>
  <module>jee-example-web-war</module>
  <module>jee-example-app-ear</module>
  <module>jee-example-app-bom</module>
</modules>
----

TIP: Be sure to reorder the list of modules if necessary so that they are listed in an appropriate build order for your project.

// TODO include link to either the repo, or to something about more info on that repo.
The root POM is also configured to use the Red Hat JBoss Enterprise Application Platform Maven repository to download project dependencies.


[[bom_file]]
===== BOM File

// TODO give more info on why they should care about this file/why it's helpful
The Bill of Materials (BOM) file is generated in the directory ending in `-bom`. For the example `jee-example-app-1.0.0.ear` application, the BOM file can be found at `/path/to/output/mavenized/jee-example-app-bom/pom.xml`. The purpose of this BOM file is to list the versions of third-party dependencies used by the project.

The following dependencies are listed in the BOM for the example `jee-example-app-1.0.0.ear` application

[source,xml,options="nowrap"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.6</version>
      <classifier></classifier>
    </dependency>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>2.5</version>
      <classifier></classifier>
    </dependency>
  </dependencies>
</dependencyManagement>
----

[[app_pom_files]]
===== Application POM Files

Each application module will have a separate directory containing its POM file. The directory name will contain the name of the archive and will end in a `-jar`, `-war`, or `-ear` suffix, depending on the archive type.

Each application POM file lists that module's dependencies, including:

* Third-party libraries
* Java EE APIs
* Application submodules

// TODO: mention that it's for the jee-example app?
For example, the POM file for the EAR, `/path/to/output/mavenized/jee-example-app-ear/pom.xml`, lists the following dependencies.

[source,xml,options="nowrap"]
----
<dependencies>
  <dependency>
    <groupId>log4j</groupId>
    <artifactId>log4j</artifactId>
    <version>1.2.6</version>
  </dependency>
  <dependency>
    <groupId>org.jboss.seam</groupId>
    <artifactId>jee-example-web-war</artifactId>
    <version>1.0</version>
    <type>war</type>
  </dependency>
  <dependency>
    <groupId>org.jboss.seam</groupId>
    <artifactId>jee-example-services-jar</artifactId>
    <version>1.0</version>
  </dependency>
  <dependency>
    <groupId>org.jboss.seam</groupId>
    <artifactId>jee-example-services2-jar</artifactId>
    <version>1.0</version>
  </dependency>
</dependencies>
----

// TODO mention other differences in POM contents for WARs vs. EARs (vs. JARs)?

